kind = "DojoModel"
class_hash = "0x501474f5ea92fb1696ca5bc715cbd5961c86e3b0ca1b2ccc6c22750f9d362d1"
original_class_hash = "0x501474f5ea92fb1696ca5bc715cbd5961c86e3b0ca1b2ccc6c22750f9d362d1"
abi = "manifests/dev/abis/base/models/retropie_models_index_game.json"
name = "retropie::models::index::game"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "short_name"
type = "felt252"
key = false

[[members]]
name = "full_name"
type = "felt252"
key = false

[[members]]
name = "rom_path"
type = "felt252"
key = false

[[members]]
name = "owner"
type = "felt252"
key = false
