kind = "DojoModel"
class_hash = "0x605ca3a20537853b1ecf5a3309154f2d25c5a087c6a3db98a811f21ad9e051d"
original_class_hash = "0x605ca3a20537853b1ecf5a3309154f2d25c5a087c6a3db98a811f21ad9e051d"
abi = "manifests/dev/abis/base/models/retropie_models_index_game.json"
name = "retropie::models::index::game"

[[members]]
name = "id"
type = "u64"
key = true

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "desc"
type = "ByteArray"
key = false

[[members]]
name = "image"
type = "ByteArray"
key = false

[[members]]
name = "rating"
type = "u8"
key = false

[[members]]
name = "releasedate"
type = "u64"
key = false

[[members]]
name = "developer"
type = "felt252"
key = false

[[members]]
name = "publisher"
type = "felt252"
key = false

[[members]]
name = "genre"
type = "felt252"
key = false

[[members]]
name = "players"
type = "u8"
key = false

[[members]]
name = "playcount"
type = "u32"
key = false

[[members]]
name = "lastplayed"
type = "u64"
key = false

[[members]]
name = "owner"
type = "felt252"
key = false
